# Docker Compose configuration for Pokemon AI Agents

services:
  api:
    build: .
    container_name: pokemon-ai-api
    ports:
      - "8088:8088"
    environment:
      - SERVICE=api
      - API_HOST=0.0.0.0
      - API_PORT=8088
      - API_DEBUG=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING:-false}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    volumes:
      - .:/app
    networks:
      - pokemon-network

  streamlit:
    build: .
    container_name: pokemon-ai-streamlit
    ports:
      - "8501:8501"
    environment:
      - SERVICE=streamlit
      - API_HOST=api
      - API_PORT=8088
      - STREAMLIT_HOST=0.0.0.0
      - STREAMLIT_PORT=8501
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge
